name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
# deactivate on push because we run this workflow from tice-fork-deployment workflow
#  push:
  workflow_call:

permissions:
  contents: read
  packages: read

jobs:
  validate-gradle-wrapper:
    name: 'Validate gradle wrapper'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v3

  build-gradle:
    name: Build
    runs-on: ubuntu-latest
    needs: [validate-gradle-wrapper]
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build with Gradle Wrapper
        run: ./gradlew build --full-stacktrace
